spring:
  application:
    name: IbankService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dbs_schema
    password: Happy@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'


server:
  port: '8085'
  servlet:
    context-path: /ibank-service

app:
  baseUrl: http://localhost:8086/ibank-movies